// Renders the standalone report PDFs (sales, tax, expenses, profit & loss)
// generated by routes/reports.js. These are tabular/statement documents,
// not the bill-to/line-items/signature shape quote/invoice/receipt PDFs
// use — but they share the same page geometry, palette, and money/image
// helpers, pulled in from lib/pdf.js rather than duplicated here.
const {
  MARGIN, CONTENT_WIDTH, PAGE_BOTTOM, COLORS,
  money, newDoc, docToBuffer, decodeImageDataUri, addPageFooter,
} = require('./pdf');

function titleCase(str) {
  return str.replace(/\b\w/g, (c) => c.toUpperCase());
}

// Net profit is the one figure on these reports that can go negative —
// every other amount (sales, tax, expenses) is always >= 0, so money()
// (which never special-cases a sign) is fine for those. toLocaleString
// already puts the minus before the digits; this just moves it in front
// of the currency symbol too, matching how the frontend's own money()
// helper (Financials.jsx) formats a possibly-negative amount.
function signedMoney(amount, symbol) {
  const sign = amount < 0 ? '-' : '';
  return `${sign}${money(Math.abs(amount), symbol)}`;
}

// Logo + business name/contact (left) and report title + period + a
// "Generated <date>" timestamp (right), closed off with a brand divider —
// the report equivalent of drawHeader/drawMinimalHeader in lib/pdf.js, but
// with no document number/TIN/prepared-by meta rows since a report isn't
// a numbered document tied to one client.
function drawReportHeader(doc, { title, subtitle, settings }) {
  const logoBuffer = settings.logo_image ? decodeImageDataUri(settings.logo_image) : null;
  const logoSize = 40;
  const nameX = logoBuffer ? MARGIN + logoSize + 10 : MARGIN;
  const nameWidth = 300 - (logoBuffer ? logoSize + 10 : 0);

  if (logoBuffer) doc.image(logoBuffer, MARGIN, 45, { fit: [logoSize, logoSize] });

  const businessName = settings.business_name || 'Your Business';
  doc.font('Helvetica-Bold').fontSize(15).fillColor(COLORS.heading).text(businessName, nameX, 48, { width: nameWidth });
  const nameHeight = doc.heightOfString(businessName, { width: nameWidth });
  let leftY = 48 + Math.max(logoBuffer ? logoSize : 0, nameHeight) + 4;

  const contactLines = [settings.address, settings.phone, settings.email].filter(Boolean).join('  ·  ');
  if (contactLines) {
    doc.font('Helvetica').fontSize(8.5).fillColor(COLORS.muted).text(contactLines, MARGIN, leftY, { width: 300 });
    leftY += doc.heightOfString(contactLines, { width: 300 });
  }
  if (settings.tax_id) {
    doc.font('Helvetica').fontSize(8.5).fillColor(COLORS.muted).text(`TIN: ${settings.tax_id}`, MARGIN, leftY + 2, { width: 300 });
    leftY += 14;
  }

  doc.font('Helvetica-Bold').fontSize(17).fillColor(COLORS.heading).text(title, 300, 48, { width: 245, align: 'right' });
  let rightY = 48 + doc.heightOfString(title, { width: 245 }) + 4;
  doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.body).text(subtitle, 300, rightY, { width: 245, align: 'right' });
  rightY += doc.heightOfString(subtitle, { width: 245 }) + 4;
  doc.font('Helvetica').fontSize(8).fillColor(COLORS.muted).text(`Generated ${new Date().toISOString().slice(0, 10)}`, 300, rightY, { width: 245, align: 'right' });
  rightY += 12;

  const dividerY = Math.max(leftY, rightY) + 10;
  doc.moveTo(MARGIN, dividerY).lineTo(MARGIN + CONTENT_WIDTH, dividerY).strokeColor(COLORS.brand).lineWidth(2).stroke();
  return dividerY + 20;
}

function drawEmptyNotice(doc, text, y) {
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.muted).text(text, MARGIN, y);
  return y + 20;
}

// `columns`: [{ key, label, x, width, align, format(row), bold }]. `x` is
// relative to MARGIN — callers lay out their own column grid (see the
// render functions below) rather than this deriving one, since each
// report's columns differ too much to share a fixed layout.
function drawTableHeaderRow(doc, columns, y) {
  doc.rect(MARGIN, y, CONTENT_WIDTH, 20).fill(COLORS.headerFill);
  doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.body);
  columns.forEach((col) => {
    doc.text(col.label, MARGIN + col.x, y + 6, { width: col.width, align: col.align || 'left' });
  });
  return y + 20;
}

// Paginates like drawItemsTable in lib/pdf.js: redraws the header row on
// any page a row overflows onto, so a long report never renders off-page.
function drawReportTable(doc, { columns, rows }, startY) {
  let y = drawTableHeaderRow(doc, columns, startY);

  rows.forEach((row, index) => {
    const rowHeight = 18;
    if (y + rowHeight > PAGE_BOTTOM) {
      doc.addPage();
      y = drawTableHeaderRow(doc, columns, MARGIN);
    }
    if (index % 2 === 1) doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).fill(COLORS.rowAlt);

    columns.forEach((col) => {
      const value = col.format ? col.format(row) : row[col.key];
      doc
        .font(col.bold ? 'Helvetica-Bold' : 'Helvetica')
        .fontSize(9)
        .fillColor(col.bold ? COLORS.heading : COLORS.body)
        .text(String(value), MARGIN + col.x, y + 5, { width: col.width, align: col.align || 'left' });
    });
    y += rowHeight;
  });

  doc.moveTo(MARGIN, y).lineTo(MARGIN + CONTENT_WIDTH, y).strokeColor(COLORS.border).stroke();
  return y + 16;
}

// Right-aligned label:value summary box — the report equivalent of
// drawTotals, but with an arbitrary caller-supplied row list instead of a
// fixed subtotal/discount/tax shape. `dividerBeforeLast` draws a rule
// above the final row (the grand total), matching drawTotals' own
// subtotal-rows/divider/bold-final-row layout.
function drawSummaryBox(doc, rows, y, { dividerBeforeLast = false } = {}) {
  const boxX = 300;
  const boxWidth = 245;
  const blockHeight = rows.length * 18 + 20;
  if (y + blockHeight > PAGE_BOTTOM) {
    doc.addPage();
    y = MARGIN;
  }

  let rowY = y;
  rows.forEach((row, index) => {
    const isLast = index === rows.length - 1;
    if (dividerBeforeLast && isLast) {
      doc.moveTo(boxX, rowY).lineTo(boxX + boxWidth, rowY).strokeColor(COLORS.border).lineWidth(1).stroke();
      rowY += 10;
    }
    const bold = row.bold || (dividerBeforeLast && isLast);
    const size = bold ? 12 : 10;
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).fillColor(row.color || COLORS.body).text(row.label, boxX, rowY, { width: 130 });
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).fillColor(row.color || COLORS.heading).text(row.value, boxX + 130, rowY, { width: 115, align: 'right' });
    rowY += bold ? 20 : 18;
  });

  return rowY + 14;
}

// One P&L section (REVENUE or EXPENSES): a brand-colored heading, an
// indented label/amount row per line item, a rule, then a bold total row
// — used twice by renderProfitLossPdf so both sections read identically.
function drawStatementSection(doc, { title, rows, totalLabel, totalValue }, y) {
  const rowHeight = 18;
  const height = 22 + rows.length * rowHeight + 34;
  if (y + height > PAGE_BOTTOM) {
    doc.addPage();
    y = MARGIN;
  }

  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.brand).text(title, MARGIN, y, { width: CONTENT_WIDTH });
  y += 22;

  rows.forEach(({ label, value }) => {
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.body).text(label, MARGIN + 12, y, { width: 320 });
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.heading).text(value, MARGIN, y, { width: CONTENT_WIDTH, align: 'right' });
    y += rowHeight;
  });

  doc.moveTo(MARGIN + 12, y + 2).lineTo(MARGIN + CONTENT_WIDTH, y + 2).strokeColor(COLORS.border).lineWidth(1).stroke();
  y += 12;
  doc.font('Helvetica-Bold').fontSize(10.5).fillColor(COLORS.heading).text(totalLabel, MARGIN + 12, y, { width: 320 });
  doc.font('Helvetica-Bold').fontSize(10.5).fillColor(COLORS.heading).text(totalValue, MARGIN, y, { width: CONTENT_WIDTH, align: 'right' });
  return y + 32;
}

// The closing "NET PROFIT"/"NET LOSS" bar — a filled rounded rect, green
// when non-negative and red otherwise (same positive/negative palette
// drawTotals uses for an invoice's Balance Due).
function drawNetProfitBar(doc, { value, positive }, y) {
  if (y + 46 > PAGE_BOTTOM) {
    doc.addPage();
    y = MARGIN;
  }
  const fill = positive ? '#ecfdf5' : '#fef2f2';
  const color = positive ? COLORS.positive : COLORS.negative;
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 42, 6).fill(fill);
  doc.font('Helvetica-Bold').fontSize(13).fillColor(color).text(positive ? 'NET PROFIT' : 'NET LOSS', MARGIN + 16, y + 14, { width: 300 });
  doc.font('Helvetica-Bold').fontSize(16).fillColor(color).text(value, MARGIN, y + 12, { width: CONTENT_WIDTH - 16, align: 'right' });
  return y + 42 + 20;
}

function renderSalesReportPdf({ invoices, from, to, settings }) {
  const doc = newDoc();
  const symbol = settings.currency_symbol || '$';
  let y = drawReportHeader(doc, { title: 'SALES REPORT', subtitle: `${from} to ${to}`, settings });

  if (invoices.length === 0) {
    drawEmptyNotice(doc, 'No invoices in this date range.', y);
    return docToBuffer(doc, (d) => addPageFooter(d, settings));
  }

  const columns = [
    { key: 'number', label: 'INVOICE #', x: 0, width: 75 },
    { key: 'client_name', label: 'CLIENT', x: 78, width: 110 },
    { key: 'issue_date', label: 'DATE', x: 190, width: 60 },
    { key: 'status', label: 'STATUS', x: 252, width: 55, format: (r) => r.status.toUpperCase() },
    { key: 'total', label: 'TOTAL', x: 309, width: 65, align: 'right', format: (r) => money(r.total, symbol) },
    { key: 'amount_paid', label: 'PAID', x: 376, width: 60, align: 'right', format: (r) => money(r.amount_paid, symbol) },
    { key: 'balance', label: 'BALANCE', x: 438, width: 57, align: 'right', format: (r) => money(r.total - r.amount_paid, symbol) },
  ];
  y = drawReportTable(doc, { columns, rows: invoices }, y);

  const totalSales = invoices.reduce((s, i) => s + i.total, 0);
  const totalPaid = invoices.reduce((s, i) => s + i.amount_paid, 0);
  y = drawSummaryBox(
    doc,
    [
      { label: 'Invoices', value: String(invoices.length) },
      { label: 'Total sales', value: money(totalSales, symbol) },
      { label: 'Total collected', value: money(totalPaid, symbol) },
      { label: 'Outstanding', value: money(totalSales - totalPaid, symbol) },
    ],
    y,
    { dividerBeforeLast: true },
  );

  return docToBuffer(doc, (d) => addPageFooter(d, settings));
}

function renderTaxReportPdf({ invoices, from, to, settings }) {
  const doc = newDoc();
  const symbol = settings.currency_symbol || '$';
  let y = drawReportHeader(doc, { title: 'TAX REPORT', subtitle: `${from} to ${to}`, settings });

  if (invoices.length === 0) {
    drawEmptyNotice(doc, 'No invoices in this date range.', y);
    return docToBuffer(doc, (d) => addPageFooter(d, settings));
  }

  // Taxable amount is the post-discount base tax_amount was actually
  // computed against — see lib/totals.js: subtotal -> discount -> tax.
  const rows = invoices.map((inv) => ({ ...inv, taxable_base: inv.subtotal - inv.discount_amount }));

  const columns = [
    { key: 'number', label: 'INVOICE #', x: 0, width: 75 },
    { key: 'client_name', label: 'CLIENT', x: 78, width: 115 },
    { key: 'issue_date', label: 'DATE', x: 196, width: 55 },
    { key: 'taxable_base', label: 'TAXABLE AMT', x: 254, width: 80, align: 'right', format: (r) => money(r.taxable_base, symbol) },
    { key: 'tax_rate', label: 'RATE', x: 337, width: 40, align: 'right', format: (r) => `${r.tax_rate}%` },
    { key: 'tax_amount', label: 'TAX', x: 380, width: 55, align: 'right', format: (r) => money(r.tax_amount, symbol) },
    { key: 'total', label: 'TOTAL', x: 438, width: 57, align: 'right', format: (r) => money(r.total, symbol) },
  ];
  y = drawReportTable(doc, { columns, rows }, y);

  const totalTaxable = rows.reduce((s, i) => s + i.taxable_base, 0);
  const totalSales = rows.reduce((s, i) => s + i.total, 0);
  const totalTax = rows.reduce((s, i) => s + i.tax_amount, 0);
  y = drawSummaryBox(
    doc,
    [
      { label: 'Invoices', value: String(invoices.length) },
      { label: 'Total taxable amount', value: money(totalTaxable, symbol) },
      { label: 'Total sales (incl. tax)', value: money(totalSales, symbol) },
      { label: 'Total tax collected', value: money(totalTax, symbol) },
    ],
    y,
    { dividerBeforeLast: true },
  );

  return docToBuffer(doc, (d) => addPageFooter(d, settings));
}

function renderExpenseReportPdf({ expenses, from, to, settings }) {
  const doc = newDoc();
  const symbol = settings.currency_symbol || '$';
  let y = drawReportHeader(doc, { title: 'EXPENSE REPORT', subtitle: `${from} to ${to}`, settings });

  if (expenses.length === 0) {
    drawEmptyNotice(doc, 'No expenses in this date range.', y);
    return docToBuffer(doc, (d) => addPageFooter(d, settings));
  }

  // Grouped by category (rows already come pre-sorted by category from the
  // route's ORDER BY) — a running Map preserves first-seen category order
  // rather than needing a separate sort pass here.
  const byCategory = new Map();
  for (const e of expenses) {
    if (!byCategory.has(e.category)) byCategory.set(e.category, []);
    byCategory.get(e.category).push(e);
  }

  const columns = [
    { key: 'expense_date', label: 'DATE', x: 0, width: 70 },
    { key: 'description', label: 'DESCRIPTION', x: 75, width: 280 },
    { key: 'amount', label: 'AMOUNT', x: 415, width: 80, align: 'right', format: (r) => money(r.amount, symbol) },
  ];

  let grandTotal = 0;
  for (const [category, rows] of byCategory) {
    if (y + 20 > PAGE_BOTTOM) {
      doc.addPage();
      y = MARGIN;
    }
    doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.brand).text(titleCase(category), MARGIN, y);
    y += 16;
    y = drawReportTable(doc, { columns, rows }, y);

    const subtotal = rows.reduce((s, r) => s + r.amount, 0);
    grandTotal += subtotal;
    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(COLORS.heading).text(`Subtotal: ${money(subtotal, symbol)}`, MARGIN, y, { width: CONTENT_WIDTH, align: 'right' });
    y += 26;
  }

  drawSummaryBox(doc, [{ label: 'Total expenses', value: money(grandTotal, symbol), bold: true }], y);

  return docToBuffer(doc, (d) => addPageFooter(d, settings));
}

function renderProfitLossPdf({ revenueTotal, expensesByCategory, totalExpenses, from, to, settings }) {
  const doc = newDoc();
  const symbol = settings.currency_symbol || '$';
  let y = drawReportHeader(doc, { title: 'PROFIT & LOSS', subtitle: `${from} to ${to}`, settings });

  y = drawStatementSection(
    doc,
    {
      title: 'REVENUE',
      rows: [{ label: 'Payments received', value: money(revenueTotal, symbol) }],
      totalLabel: 'Total revenue',
      totalValue: money(revenueTotal, symbol),
    },
    y,
  );

  const expenseRows = expensesByCategory.map((c) => ({ label: titleCase(c.category), value: money(c.total, symbol) }));
  y = drawStatementSection(
    doc,
    {
      title: 'EXPENSES',
      rows: expenseRows.length ? expenseRows : [{ label: 'No expenses recorded', value: money(0, symbol) }],
      totalLabel: 'Total expenses',
      totalValue: money(totalExpenses, symbol),
    },
    y,
  );

  const netProfit = Math.round((revenueTotal - totalExpenses) * 100) / 100;
  y = drawNetProfitBar(doc, { value: signedMoney(netProfit, symbol), positive: netProfit >= 0 }, y);

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text('Revenue is cash actually received (payments recorded) during this period; expenses are recorded on the date incurred.', MARGIN, y, { width: CONTENT_WIDTH });

  return docToBuffer(doc, (d) => addPageFooter(d, settings));
}

// Opening/closing balance, same starting_balance + net-of-payments-and-
// expenses math as routes/financials.js's bankBalance, just anchored to
// the period's `from`/`to` dates instead of "as of right now" — opening
// balance is starting_balance plus everything recorded strictly before
// `from`, closing balance is the same plus everything up to and including
// `to`. A single drawSummaryBox (not two drawStatementSection blocks like
// P&L) since this is a short four-line reconciliation, not a
// category-by-category breakdown.
function renderBankBalancePdf({ openingBalance, totalPayments, totalContributions, totalExpenses, closingBalance, from, to, settings }) {
  const doc = newDoc();
  const symbol = settings.currency_symbol || '$';
  let y = drawReportHeader(doc, { title: 'BANK BALANCE STATEMENT', subtitle: `${from} to ${to}`, settings });

  const rows = [{ label: 'Opening balance', value: signedMoney(openingBalance, symbol) }, { label: 'Payments received', value: money(totalPayments, symbol) }];
  // Only shown when relevant — most businesses never have one, and a
  // zero-value "Capital contributions" row on every statement would just be
  // noise for the common case.
  if (totalContributions) rows.push({ label: 'Capital contributions', value: money(totalContributions, symbol) });
  rows.push(
    { label: 'Expenses', value: signedMoney(-totalExpenses, symbol) },
    { label: 'Closing balance', value: signedMoney(closingBalance, symbol), bold: true },
  );

  y = drawSummaryBox(doc, rows, y, { dividerBeforeLast: true });

  doc
    .font('Helvetica')
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(
      "Opening balance is the starting balance set in Settings plus every payment received and capital contribution recorded before this period, minus expenses. Not a live bank feed — money moving outside this app (loans, tax remittances) isn't reflected.",
      MARGIN,
      y,
      { width: CONTENT_WIDTH },
    );

  return docToBuffer(doc, (d) => addPageFooter(d, settings));
}

module.exports = { renderSalesReportPdf, renderTaxReportPdf, renderExpenseReportPdf, renderProfitLossPdf, renderBankBalancePdf };
